### ISSUE TITLE
Unit tests failing

### ISSUE THREAD

**Issue by blinkdog** [WIPACrepo/file_catalog#13]
```
pmeade@titan ~/NetBeansProjects/file_catalog $ python -m unittest discover
EEE
======================================================================
ERROR: test_01_HATEOAS (tests.test_server.TestServerAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pmeade/NetBeansProjects/file_catalog/tests/test_server.py", line 30, in setUp
    '--logpath', dblog])
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

======================================================================
ERROR: test_10_files (tests.test_server.TestServerAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pmeade/NetBeansProjects/file_catalog/tests/test_server.py", line 30, in setUp
    '--logpath', dblog])
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

======================================================================
ERROR: test_20_file (tests.test_server.TestServerAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pmeade/NetBeansProjects/file_catalog/tests/test_server.py", line 30, in setUp
    '--logpath', dblog])
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

----------------------------------------------------------------------
Ran 3 tests in 0.011s

FAILED (errors=3)
```

**Comment by dsschult** [comment]
I fixed the path to the config file in c88ebb3.

But I think your error is not having mongod installed.

**Comment by blinkdog** [comment]
I do have a local installation of MongoDB:
```
pmeade@titan ~/NetBeansProjects/file_catalog $ which mongod
/home/pmeade/mongodb-linux-x86_64-ubuntu1604-3.4.2/bin/mongod
```

Do the unit tests require a canonical system installation?

**Comment by blinkdog** [comment]
I just thought your comment might also refer to not having a mongod running.
Alas, that did not make the unit tests pass either.
```
Ran 3 tests in 1.264s

FAILED (errors=3)
pmeade@titan ~/NetBeansProjects/file_catalog $ ps aux | grep mongod
pmeade    5321  3.5  0.7 268944 56232 pts/3    Sl+  08:40   0:00 mongod --dbpath /mnt/data/mongo
pmeade    5368  0.0  0.0  14224  1088 pts/2    S+   08:40   0:00 grep --color=auto mongod
```

**Comment by dsschult** [comment]
I thought all it needed was for mongod to be in the PATH.  What happens if you try this?

```python -c 'import subprocess;subprocess.call(["mongod"])'```

**Comment by blinkdog** [comment]
Maybe it's that I've got a non-standard `dbpath`?
```
pmeade@titan ~ $ python -c 'import subprocess;subprocess.call(["mongod"])'
2017-02-24T14:11:57.949-0600 I CONTROL  [initandlisten] MongoDB starting : pid=13568 port=27017 dbpath=/data/db 64-bit host=titan
2017-02-24T14:11:57.949-0600 I CONTROL  [initandlisten] db version v3.4.2
2017-02-24T14:11:57.949-0600 I CONTROL  [initandlisten] git version: 3f76e40c105fc223b3e5aac3e20dcd026b83b38b
2017-02-24T14:11:57.949-0600 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2017-02-24T14:11:57.949-0600 I CONTROL  [initandlisten] allocator: tcmalloc
2017-02-24T14:11:57.949-0600 I CONTROL  [initandlisten] modules: none
2017-02-24T14:11:57.949-0600 I CONTROL  [initandlisten] build environment:
2017-02-24T14:11:57.949-0600 I CONTROL  [initandlisten]     distmod: ubuntu1604
2017-02-24T14:11:57.949-0600 I CONTROL  [initandlisten]     distarch: x86_64
2017-02-24T14:11:57.949-0600 I CONTROL  [initandlisten]     target_arch: x86_64
2017-02-24T14:11:57.949-0600 I CONTROL  [initandlisten] options: {}
2017-02-24T14:11:58.024-0600 I STORAGE  [initandlisten] exception in initAndListen: 29 Data directory /data/db not found., terminating
2017-02-24T14:11:58.024-0600 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2017-02-24T14:11:58.024-0600 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
2017-02-24T14:11:58.024-0600 I CONTROL  [initandlisten] now exiting
2017-02-24T14:11:58.024-0600 I CONTROL  [initandlisten] shutting down with code:100
```

**Comment by blinkdog** [comment]
```
pmeade@titan ~/NetBeansProjects/file_catalog $ git diff
diff --git a/tests/test_server.py b/tests/test_server.py
index 83c0081..877476e 100644
--- a/tests/test_server.py
+++ b/tests/test_server.py
@@ -37,7 +37,7 @@ class TestServerAPI(unittest.TestCase):
                               '--debug',
                               '--config', 'resources/server.cfg'])
         self.addCleanup(s.terminate)
-        time.sleep(0.3)
+        time.sleep(1)
 
     def curl(self, url, method='GET', args=None, prefix='/api', headers=None):
         cmd = ['curl', '-X', method, '-s', '-i']
[1]+  Done                    xed tests/test_server.py
```
